---
vagrantfile-local:
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        hostname: ''
        memory: '1024'
        cpus: '2'
        chosen_provider: virtualbox
        sync_modules: true
        network:
            private_network: 192.168.9.10
            forwarded_port:
                5tryP4ZFTBV9:
                    host: '8888'
                    guest: '80'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            wRT5TsSy6sE4:
                source: ./
                target: /var/www
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages:
        - build-essential
        - vim
        - curl
        - git-core
        - php-console-table
        - imagemagick
        - sendmail
        - unzip
        - mc
        - graphviz
        - memcached
        - libssh2-1-dev
        - libmemcached-dev
        - htop
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
firewall:
    install: '1'
    rules:
      xdebug:
        port: 9000
        proto: tcp
        action: accept
        priority: 9000
apache:
    install: 1
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        0M1pWVWI2bhY:
            servername: druphpet.dev
            serveraliases:
                - www.druphpet.dev
            docroot: /var/www/druphpet
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            options:
                - Indexes
                - FollowSymLinks
                - MultiViews
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: '0'
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    vhosts:
        VTChGNgY0tNd:
            server_name: druphpet.dev
            server_aliases:
                - www.druphpet.dev
            www_root: /var/www/druphpet.dev
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            spdy: '1'
php:
    install: '1'
    version: '55'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - curl
            - gd
        pear:
            - PHP_CodeSniffer
        pecl:
            - pecl_http
            - uploadprogress
            - apcu
            - ssh2-0.12
            - memcached
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        memory_limit: '512M'
        upload_max_filesize: '128M'
        post_max_size: '128M'
        max_execution_time: '300'
        apc.shm_size: '128M'
        apc.ttl: '0'
        apc.gc_ttl: '600'
        apc.enable_cli: '1'
        apc.mmap_file_mask: '/tmp/apc.XXXXXX'
        error_log: /var/log/php_errors.log
    timezone: Europe/Minsk
    mod_php: '1'
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_host: 'localhost'
        xdebug.remote_enable: '1'
        xdebug.remote_port: '9000'
        xdebug.max_nesting_level: '5000'
xhprof:
    install: '1'
drush:
    install: '1'
    version: 7.0.0-alpha5
ruby:
    install: '1'
    versions:
        hRDoJFjOLzkH:
            default: '1'
            version: 1.9.3
            gems:
                - sass
                - compass
                - guard
                - livereload
            bundler: '1'
nodejs:
    install: '1'
    npm_packages:
        - yo
        - generator-angular
        - gulp
        - bower
        - coffee-script
        - jshint
        - csslint
        - jslint
        - nodemon
        - grunt-cli
mysql:
    install: 1
    root_password: 'druphpet'
    adminer: 1
    databases:
        gPB9UXozXZEq:
            grant:
                - ALL
            name: druphpet
            host: '%'
            user: druphpet
            password: 'druphpet'
            sql_file: ''
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: '0'
mariadb:
    install: '0'
    root_password: 'druphpet'
    adminer: '1'
    databases: {}
    version: '10.0'
sqlite:
    install: '0'
    adminer: '0'
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        java_install: true
        autoupgrade: true
samba_server:
    install: '1'
php_memcached:
    install: '0'
solr:
    install: '0'
pimpmylog:
    install: '1'
varnish:
    install: '0'
    settings:
        http_port: 8080
        storage_size: 0.5G
webgrind:
    install: '1'
    domain: 'webgrind.druphpet.dev'
newrelic:
    install: '0'
    application_name: 'druphpet'
    license_key: ''
